import { Location, PendingPermit } from "./types";

export const DEFAULT_LOCATIONS: Location[] = [
  {
    id: "zongo",
    title: "Chutes de Zongo",
    locationName: "Zongo (Kongo Central)",
    category: "Nature",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBE4DWbgQW_fr9hp5JhT4E3bRhsyNzEIx1muN5mc9ImNkBzDfpWziSG_sZykNBeNH8faXu-HcO-aOEi1jKkyp0rVx9YUIIOmPXD3M_4CSG0lhG71jQ4Lzlqmr6cwo_KGj6L5A6PV3BLuERIG0MzkUD-MAMNDC4N7wUIRIdy-y293R6R9EF0hz1nCUKUbuIiS5U1u2fKX_Hbtpc1FBNO3-6V0HerxVT7aSiziMjjpeKVbkAIBrlLe9M9oQ",
    description: "Découvrez la puissance brute de la nature au cœur du Kongo Central. Une expérience inoubliable avec des chutes d'eau spectaculaires de 65 mètres s'écrasant avec fracas dans un écrin de forêt dense.",
    status: "PUBLISHED",
    coords: { x: 58, y: 32 },
    lat: -4.7825,
    lng: 14.3541,
    rating: 4.9,
    timeToVisit: "4 heures",
    cognitiveEffort: 65,
    intensity: "Intensité Modérée",
    terrain: "Terrain humide et forestier",
    currentStatus: "Le débit est exceptionnel et magnifique aujourd'hui. Brume intense l'après-midi.",
    history: "Ancien site spirituel pour les populations locales Ne-Kongo, Zongo signifie \"bruit de tonnerre\" en langue Kikongo. Les chutes ont longtemps servi de repère culturel majeur et de barrière naturelle protectrice. Le site témoigne du lien intime que les communautés locales entretiennent avec les forces de l'eau.",
    checklist: ["Imperméable léger", "Chaussures de marche antidérapantes", "Gourde d'eau réutilisable", "Produit anti-moustique"],
    bestSeason: "Saison sèche (juin à septembre) pour des pistes plus faciles, ou fin de saison des pluies (mai) pour un débit maximal impressionnant.",
    safetyGuidelines: "Restez impérativement sur les sentiers balisés. Les rochers près des chutes sont extrêmement glissants en raison de l'humidité constante.",
    ecoResponsibility: "Ramenez tous vos emballages et déchets à Kinshasa ou Matadi. Ne laissez aucune trace plastique dans cet écosystème forestier fragile.",
    localCustoms: "Salué poliment les écogardes et les habitants des villages environnants. Le respect mutuel est au cœur des valeurs locales."
  },
  {
    id: "grottes_mbanza",
    title: "Grottes de Mbanza-Ngungu",
    locationName: "Mbanza-Ngungu",
    category: "Incontournables",
    image: "https://images.unsplash.com/photo-1507163546605-a84d8ff1a23e?w=800",
    description: "Un réseau fascinant de cavernes calcaires abritant des espèces de poissons aveugles et lucifuges uniques au monde (Caecobarbus geertsii), enveloppées de légendes mystiques et d'une géologie impressionnante.",
    status: "PUBLISHED",
    coords: { x: 50, y: 48 },
    lat: -5.2500,
    lng: 14.8667,
    rating: 4.9,
    timeToVisit: "3 heures",
    cognitiveEffort: 65,
    intensity: "Randonnée Modérée",
    terrain: "Cavernes et roches calcaires",
    currentStatus: "Ouvert. Des guides locaux formés vous attendent à l'entrée principale.",
    history: "Ces grottes ont servi de refuge et de lieu de recueillement spirituel aux ancêtres du peuple Kongo. Elles abritent un écosystème souterrain d'intérêt mondial étudié par les spéléologues depuis le début du XXe siècle.",
    checklist: ["Lampe frontale puissante", "Chaussures de marche antidérapantes", "Vêtements longs", "Eau potable"],
    bestSeason: "Saison sèche (juin à septembre) pour éviter les infiltrations d'eau torrentielles.",
    safetyGuidelines: "Le port du casque et l'accompagnement par un guide local agréé sont indispensables. Ne vous aventurez jamais seul dans les galeries.",
    ecoResponsibility: "Ne touchez pas aux stalactites ni aux poissons aveugles. Ne laissez aucun déchet plastique à l'intérieur du réseau souterrain.",
    localCustoms: "Avant d'entrer, le guide traditionnel effectue parfois un rituel d'invocation symbolique pour demander l'accord des esprits gardiens des grottes."
  },
  {
    id: "boma",
    title: "Cité Historique de Boma",
    locationName: "Boma",
    category: "Histoire",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCM6iu2Cl21PTD-o9BasImXHQBtiNtZWsLP7IprWHMxr-8TjyWtgtcY4n3KNTJDZW2mv7vDDAyFDNzAMg-46o9LRBA-FKza-2Smv8UClO_a7ZuJll5gYdi8_jjMK218caYplxWBXjujwqbt2eoWHGUOhfZSuVqloQONWV3QgmMofOXXPNeLMA2Kfo-hvvTX75bHS1bwWx6yi6EgcC-Ba8e0IlxzaZ67GJUKnfa31IxtIFYu8nAFLj-SGA",
    description: "Ancienne capitale de l'État Indépendant du Congo puis du Congo Belge, Boma conserve d'immenses trésors historiques, dont le célèbre Baobab de Stanley et la première église métallique d'Afrique.",
    status: "PUBLISHED",
    coords: { x: 18, y: 72 },
    lat: -5.8500,
    lng: 13.0500,
    rating: 4.7,
    timeToVisit: "5 heures",
    cognitiveEffort: 40,
    intensity: "Balade tranquille",
    terrain: "Urbain et plat",
    currentStatus: "Accès libre aux monuments historiques. Guides communautaires disponibles sur place.",
    history: "Boma fut un port fluvial crucial et la capitale du pays de 1886 à 1926, avant d'être remplacée par Léopoldville (Kinshasa). Son patrimoine raconte les récits d'explorateurs, d'échanges précoloniaux et les heures sombres de l'époque coloniale.",
    checklist: ["Chapeau de soleil", "Crème solaire respectueuse", "Appareil photo", "Carnet de notes"],
    bestSeason: "Toute l'année. Les brises du fleuve Congo rendent la chaleur plus supportable l'après-midi.",
    safetyGuidelines: "La circulation dans la cité est sûre, mais soyez attentif lors de la traversée des grandes rues près du port.",
    ecoResponsibility: "Évitez d'acheter des souvenirs fabriqués à partir d'espèces animales ou végétales menacées.",
    localCustoms: "Il est traditionnel de saluer l'aîné d'un groupe ou d'une communauté que l'on visite pour obtenir sa bienveillante orientation."
  },
  {
    id: "boma_baobab",
    title: "Le Baobab de Stanley",
    locationName: "Boma (Kongo Central)",
    category: "Histoire",
    image: "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=800",
    description: "Un arbre légendaire et multicentenaire ayant servi de bureau et de refuge à l'explorateur Henry Morton Stanley.",
    status: "PUBLISHED",
    coords: { x: 17, y: 72 },
    lat: -5.8591,
    lng: 13.0512,
    rating: 4.8,
    timeToVisit: "1 heure",
    cognitiveEffort: 20,
    intensity: "Balade tranquille",
    terrain: "Urbain et plat",
    currentStatus: "Accessible librement tous les jours. Un guide local est souvent disponible à proximité.",
    history: "Ce gigantesque baobab creux (Adansonia digitata), vieux de plusieurs siècles, a acquis une renommée internationale lorsque l'explorateur Henry Morton Stanley s'y est abrité en août 1877 à la fin de sa mémorable traversée d'est en ouest du continent africain. L'arbre a également servi de bureau de poste improvisé et de lieu de halte pour les premiers caravaniers. C'est un symbole vivant de la rencontre entre l'histoire de l'exploration européenne et la mémoire collective congolaise.",
    checklist: ["Appareil photo", "Chapeau de soleil", "Anti-moustique"],
    bestSeason: "Toute l'année. Les matinées sont plus fraîches pour apprécier le site à l'ombre.",
    safetyGuidelines: "Ne tentez pas d'escalader l'arbre ou d'écrire sur son écorce afin de préserver ce patrimoine fragile unique.",
    ecoResponsibility: "Ne laissez aucun déchet ou emballage plastique aux alentours de l'arbre historique.",
    localCustoms: "Saluez respectueusement les gardiens locaux du site. Les photographies à but éducatif et personnel sont encouragées."
  },
  {
    id: "boma_cathedrale",
    title: "Cathédrale Notre-Dame de l'Assomption",
    locationName: "Boma (Kongo Central)",
    category: "Incontournables",
    image: "https://images.unsplash.com/photo-1548625361-155de0cbb55a?w=800",
    description: "La toute première cathédrale catholique de la RDC, chef-d'œuvre architectural importé en kit de fer forgé en 1890.",
    status: "PUBLISHED",
    coords: { x: 19, y: 72 },
    lat: -5.8584,
    lng: 13.0565,
    rating: 4.9,
    timeToVisit: "1h30",
    cognitiveEffort: 35,
    intensity: "Balade tranquille",
    terrain: "Urbain et pavé",
    currentStatus: "Ouverte au public en dehors des heures de culte. Accueil chaleureux des guides paroissiaux.",
    history: "Consacrée en septembre 1890, cette cathédrale historique est le berceau de la christianisation moderne en République Démocratique du Congo. Entièrement préfabriquée en Belgique par les célèbres ateliers Cockerill, sa structure monumentale en fer forgé et plaques d'acier fut transportée par bateau à vapeur à travers l'océan, puis assemblée de toutes pièces sur place. L'église de fer adjacente témoigne du défi technique exceptionnel de l'époque coloniale et de l'adaptation architecturale aux climats tropicaux.",
    checklist: ["Tenue respectueuse", "Appareil photo", "Contribution volontaire pour la paroisse"],
    bestSeason: "Toute l'année, particulièrement durant les fêtes patronales de l'Assomption en août.",
    safetyGuidelines: "Suivez scrupuleusement les consignes de visite à l'intérieur. Évitez de toucher aux éléments de ferronnerie historiques très fragiles.",
    ecoResponsibility: "Préservez le calme, le silence et la propreté absolue de l'enceinte paroissiale historique.",
    localCustoms: "Une tenue décente et respectueuse est de rigueur. Retirez les couvre-chefs à l'intérieur et demandez l'autorisation avant de prendre des photos."
  },
  {
    id: "boma_fort",
    title: "Fort de Shinkakasa",
    locationName: "Boma (Kongo Central)",
    category: "Histoire",
    image: "https://images.unsplash.com/photo-1590073844006-33379778ae09?w=800",
    description: "Une impressionnante forteresse militaire de la fin du XIXe siècle construite pour protéger l'accès au fleuve Congo.",
    status: "PUBLISHED",
    coords: { x: 15, y: 73 },
    lat: -5.8427,
    lng: 13.0033,
    rating: 4.6,
    timeToVisit: "2 heures",
    cognitiveEffort: 50,
    intensity: "Marche modérée",
    terrain: "Sentiers herbeux et ruines",
    currentStatus: "Ouvert. Visites conseillées en matinée avec un guide local en raison de la végétation tropicale enveloppant les ruines.",
    history: "Construit entre 1891 et 1897 sous l'autorité de l'État Indépendant du Congo, le Fort de Shinkakasa fut conçu comme une forteresse moderne en briques et béton armé pour repousser toute incursion navale ennemie sur le fleuve Congo. Le fort fut également le théâtre de la célèbre révolte des soldats de Shinkakasa en 1900 contre les traitements infligés par les officiers de la Force Publique. Aujourd'hui, ses ruines majestueuses recouvertes par la jungle racontent l'histoire militaire complexe et les luttes héroïques de résistance africaine.",
    checklist: ["Bonnes chaussures de marche", "Lampe de poche", "Protection anti-moustique", "Eau potable"],
    bestSeason: "Saison sèche (juin à septembre) pour un accès plus aisé à travers les pistes forestières.",
    safetyGuidelines: "Certaines galeries souterraines et remparts peuvent être instables ou sombres. L'accompagnement par un guide local expérimenté est impératif.",
    ecoResponsibility: "Aucun prélèvement de briques historiques ou d'artefacts n'est toléré. Respectons la conservation matérielle du fort.",
    localCustoms: "Une demande courtoise de visite aux chefs de communauté locale permet d'accéder au site en toute sérénité."
  },
  {
    id: "boma_residence_gouverneur",
    title: "Résidence du Premier Gouverneur Général",
    locationName: "Boma (Kongo Central)",
    category: "Histoire",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800",
    description: "La première demeure coloniale métallique préfabriquée d'Afrique centrale, surplombant le fleuve depuis le Plateau.",
    status: "PUBLISHED",
    coords: { x: 18, y: 71 },
    lat: -5.8542,
    lng: 13.0560,
    rating: 4.7,
    timeToVisit: "1 heure",
    cognitiveEffort: 30,
    intensity: "Balade tranquille",
    terrain: "Urbain sur colline",
    currentStatus: "Accessible en journée. Possibilité de visiter les extérieurs et une partie de l'intérieur.",
    history: "Installée sur les hauteurs du quartier Fischier (Plateau) en 1889, cette élégante bâtisse métallique sur pilotis fut la demeure officielle des premiers Gouverneurs Généraux de l'État Indépendant du Congo. Conçue entièrement en plaques de fer boulonnées importées d'Europe pour résister aux termites et au climat tropical, elle symbolise le pouvoir politique centralisé de l'époque où Boma régnait en tant que capitale administrative suprême du pays.",
    checklist: ["Chapeau de soleil", "Lunettes de soleil", "Appareil photo", "Carnet d'histoire"],
    bestSeason: "Toute l'année. Les fins d'après-midi offrent des couchers de soleil splendides sur le fleuve Congo depuis ce promontoire.",
    safetyGuidelines: "Marchez avec précaution sur les balustrades et escaliers métalliques d'origine qui sont en cours de préservation.",
    ecoResponsibility: "Ne jetez rien sur les pelouses du domaine. Respectez la beauté florale et architecturale de la colline.",
    localCustoms: "La colline du Plateau abrite plusieurs administrations. Adoptez un comportement calme et courtois envers les riverains et le personnel."
  },
  {
    id: "luki_biosphere",
    title: "Réserve de biosphère de Luki",
    locationName: "Mayombe / Boma",
    category: "Nature",
    image: "https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=800",
    description: "Un joyau de biodiversité forestière s'étendant sur plus de 33 000 hectares au cœur du Mayombe.",
    status: "PUBLISHED",
    coords: { x: 22, y: 55 },
    lat: -5.6181,
    lng: 13.1021,
    rating: 5.0,
    timeToVisit: "Journée entière",
    cognitiveEffort: 70,
    intensity: "Randonnée intense",
    terrain: "Forêt dense et accidentée",
    currentStatus: "Ouverte aux expéditions scientifiques et éco-touristiques agréées par l'INERA.",
    history: "Établie en 1937 et reconnue Réserve de biosphère par l'UNESCO en 1979, la réserve de Luki préserve une relique inestimable de la forêt tropicale humide primaire du Mayombe. Elle sert de laboratoire naturel mondial pour l'étude de la faune (singes, éléphants de forêt, oiseaux rares) et d'arbres tropicaux de grande valeur comme le Limba et le Tola. Elle incarne le combat pour le développement durable et l'alliance précieuse entre les populations locales de l'ethnie Yombe et les chercheurs scientifiques.",
    checklist: ["Chaussures de randonnée étanches", "Vêtements longs", "Répulsif moustique tropical", "Sac à dos imperméable", "Eau potable et rations"],
    bestSeason: "Saison sèche (juin à septembre) ou petite saison sèche (janvier-février) pour éviter les pistes de boue glissantes.",
    safetyGuidelines: "Ne vous engagez jamais sans un écogarde agréé et un guide naturaliste certifié de l'INERA. La faune sauvage et l'immensité de la forêt exigent une vigilance constante.",
    ecoResponsibility: "Charte de préservation stricte : interdiction absolue d'allumer des feux non contrôlés ou d'abandonner des déchets plastiques. Ramenez tout avec vous.",
    localCustoms: "Les villages situés en lisière de la réserve ont des structures coutumières fortes. Un salut traditionnel respectueux aux chefs de terre locaux est organisé avant de pénétrer dans certaines vallées sacrées."
  },
  {
    id: "kisantu",
    title: "Jardin Botanique de Kisantu",
    locationName: "Kisantu",
    category: "Nature",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAhb1rUs7G98Mqkfz_qKj82cPjQqYlunFOrpZjt7SPHM59x1zvsklof1ZEgNMHFK0O2H4Inu4GdnhYOwWH6QkvPfI63mT86wPNav7eVSvhOWhBYE9sgT9nviWHIFEG4BOyUeTdfGDcSYD9CzhiP_nF62-pPMZ8nas35IuVLBzAM6Ncpj3pOY-XAf9eVW3DgB769Tl7l2ZCSxCt_zquYuH5JaE67yEVp_gkoAjre2UhKRobel_FunlgjnQ",
    description: "Un chef-d'œuvre de conservation environnementale couvrant 225 hectares. Abrite des arbres centenaires majeurs, une impressionnante collection de cactus exotiques et un arboretum tropical d'une valeur inestimable.",
    status: "PUBLISHED",
    coords: { x: 50, y: 40 },
    lat: -4.6125,
    lng: 15.1053,
    rating: 4.8,
    timeToVisit: "4 heures",
    cognitiveEffort: 30,
    intensity: "Balade relaxante",
    terrain: "Sentiers de terre herbeux",
    currentStatus: "Serres et chemins de randonnée botaniques ouverts de 09h00 à 17h00.",
    history: "Fondé en 1900 par le botaniste jésuite Justin Gillet, ce jardin est l'un des plus anciens et prestigieux centres de recherche et d'introduction de plantes tropicales en Afrique centrale.",
    checklist: ["Gourde d'eau", "Carnet de dessin botanique", "Protection anti-moustique", "Sandales de marche confortables"],
    bestSeason: "Idéal toute l'année, particulièrement fleuri pendant la transition des saisons en octobre et mai.",
    safetyGuidelines: "Respectez les panneaux indicateurs et ne touchez pas aux plantes inconnues ou toxiques dans les serres de cactus.",
    ecoResponsibility: "Interdiction formelle de cueillir des fleurs, des graines ou de prélever des boutures. Protégeons ce réservoir génétique unique.",
    localCustoms: "Le jardin est un lieu de paix et de contemplation. Veillez à respecter le silence des lieux et l'environnement des chercheurs."
  },
  {
    id: "pont_marechal",
    title: "Pont Maréchal Mobutu",
    locationName: "Matadi",
    category: "Urbain",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuB5ooNO7SaID7FcbrgR4Rz6xsIQ-oHVq-bOZ01yH8ycDb9NOuQiKV1aooG2RrLBBnwDX4tLnRR8riIuaPQ8A_IyT45kI3v1bUo4r9mRHFKwE1okMl4f-VIRxg5L6a4UHSSIriC8dcvmEbmavGwke1d0ALq4ng37Rwh3hAhIhiXw61S4xBv7SfvaUBmON5EpEMHRExWtbx5QOSBMhrOhksbRIZMDBbAQvnQvVrwacd5tvzljismWXQUKMw",
    description: "Une prouesse d'ingénierie moderne enjambant le majestueux fleuve Congo à Matadi. Ce pont suspendu de 722 mètres de long offre des panoramas époustouflants sur les collines et les courants violents du fleuve.",
    status: "PUBLISHED",
    coords: { x: 26, y: 65 },
    lat: -5.8144,
    lng: 13.4475,
    rating: 4.8,
    timeToVisit: "2 heures",
    cognitiveEffort: 25,
    intensity: "Intensité Légère",
    terrain: "Aménagé / Trottoirs",
    currentStatus: "Passage piéton autorisé sur les voies latérales de sécurité pour observer la vue.",
    history: "Inauguré en 1983, ce pont majestueux a été conçu par un consortium japonais. Il demeure un lien économique et humain absolument vital reliant le port de Boma à la métropole de Matadi et à Kinshasa.",
    checklist: ["Pièce d'identité", "Lunettes de soleil", "Chapeau avec cordon (fort vent)"],
    bestSeason: "Superbe au coucher de soleil, lorsque la lumière dorée se reflète sur les méandres du fleuve Congo.",
    safetyGuidelines: "Tenez fermement vos téléphones et objets personnels. Le vent peut souffler extrêmement fort au milieu du tablier.",
    ecoResponsibility: "Ne jetez absolument rien par-dessus bord dans le fleuve. L'eau est la vie des populations en aval.",
    localCustoms: "Demandez conseil aux gardiens du pont si vous souhaitez prendre des photographies des installations d'ingénierie."
  },
  {
    id: "parc_mangroves",
    title: "Parc Marin des Mangroves",
    locationName: "Muanda",
    category: "Nature",
    image: "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=800",
    description: "Une réserve naturelle protégée unique à l'embouchure du fleuve Congo. Explorez en pirogue des labyrinthes de mangroves abritant des lamantins d'Afrique, des tortues marines et une avifaune exceptionnelle.",
    status: "PUBLISHED",
    coords: { x: 8, y: 75 },
    lat: -5.9220,
    lng: 12.3550,
    rating: 4.9,
    timeToVisit: "5 heures",
    cognitiveEffort: 45,
    intensity: "Balade en pirogue",
    terrain: "Milieu humide et aquatique",
    currentStatus: "Excursions fluviales disponibles tous les matins au départ de Muanda.",
    history: "Créé en 1992, ce parc de 768 km² protège l'une des zones humides les plus riches d'Afrique centrale. C'est le seul parc marin de la République Démocratique du Congo, indispensable à l'équilibre écologique côtier.",
    checklist: ["Gilet de sauvetage (fourni)", "Chapeau de soleil", "Crème solaire bio", "Jumelles d'observation"],
    bestSeason: "De juin à octobre, période idéale pour observer l'avifaune migratrice sans les fortes averses.",
    safetyGuidelines: "Suivez strictement les consignes du piroguier. Ne tentez pas de vous baigner dans les zones de forts courants fluviaux.",
    ecoResponsibility: "N'utilisez pas de crème solaire contenant des produits chimiques nocifs pour la faune marine. Ne jetez aucun déchet dans l'eau.",
    localCustoms: "Respectez le calme de la mangrove. Les pêcheurs locaux partagent ces eaux ; un salut chaleureux en kikongo (Mbote !) est toujours apprécié."
  }
];

export const DEFAULT_PENDING_PERMITS: PendingPermit[] = [
  {
    id: "aide_eco_guard",
    title: "Reforestation Kisantu",
    subtitle: "Rapport de reboisement en cours de validation",
    status: "VERIFICATION",
    icon: "park"
  },
  {
    id: "check_customs_prep",
    title: "Charte éco de Muanda",
    subtitle: "En cours d'examen par la communauté locale",
    status: "PENDING",
    icon: "library_books"
  },
  {
    id: "check_customs_prep_2",
    title: "Checklist Respect Coutumier",
    subtitle: "En cours de lecture et validation locale",
    status: "PENDING",
    icon: "library_books"
  }
];
